ls:
  .dir: regex:\.?[a-z0-9]+(-[a-z0-9]+)*
  .*: regex:[a-z0-9]*([._][a-z0-9]+)*

ignore:
  - .git
  - .direnv
  - result
  - result-*
  - docs/logs

  - README.md

  - .venv
  - .coverage
  - .uv-cache
  - .ruff_cache
  - .pytest_cache
  - .ipynb_checkpoints
  - "src/**/__pycache__"
  - "src/**/__init__.py"
  - "tests/**/__pycache__"
  - "tests/**/__init__.py"
  - dist
  - build
